fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
home:
   path: /
   controller: App\Controller\HomeController::index


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
